import { NotificationRecord } from "@/types";

export const mockNotifications: NotificationRecord[] = [
  {
    id: 1,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "New Task Assigned",
    message: "Task #247 assigned to Rajesh Kumar for BSNL AMC work",
    type: "Task",
    is_read: false,
    link: "/tasks?id=247",
    meta: { task_id: 247, employee_id: 101 },
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "Bill Payment Due",
    message: "AMC Bill #INV-2025-034 for ₹25,000 due tomorrow",
    type: "Bill",
    is_read: false,
    link: "/amcs?bill=INV-2025-034",
    meta: { bill_number: "INV-2025-034", amount: 25000 },
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "Tender Deadline Approaching",
    message: "BSNL Network Expansion tender closes in 3 days",
    type: "Tender",
    is_read: false,
    link: "/tenders?id=5",
    meta: { tender_id: 5, days_remaining: 3 },
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "Payroll Ready for October",
    message: "Payroll for 8 employees ready for review and payment",
    type: "Payroll",
    is_read: true,
    link: "/payroll",
    meta: { period: "October 2025", employee_count: 8 },
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "System Backup Completed",
    message: "Daily backup completed successfully at 2:00 AM",
    type: "System",
    is_read: true,
    link: "/settings",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "Holiday Calendar Updated",
    message: "5 new holidays added for 2025",
    type: "System",
    is_read: true,
    link: "/settings?tab=holidays",
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 7,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "Task Completed",
    message: "Amit Patel completed task #245 - Equipment installation",
    type: "Task",
    is_read: true,
    link: "/tasks?id=245",
    meta: { task_id: 245, employee_id: 103 },
    created_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 8,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "AMC Renewal Reminder",
    message: "AMC #AMC-2024-012 for TechCorp expires in 15 days",
    type: "Reminder",
    is_read: true,
    link: "/amcs?id=12",
    meta: { amc_id: 12, days_until_expiry: 15 },
    created_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 9,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "Payment Received",
    message: "Payment of ₹45,000 received from DataNet Solutions",
    type: "Bill",
    is_read: true,
    link: "/clients?id=5",
    meta: { amount: 45000, client_id: 5 },
    created_at: new Date(Date.now() - 144 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 10,
    recipient_id: 1,
    recipient_name: "Owner",
    title: "New Client Onboarded",
    message: "GlobalNet Inc. added as new client with 2 AMCs",
    type: "System",
    is_read: true,
    link: "/clients?id=8",
    meta: { client_id: 8, amc_count: 2 },
    created_at: new Date(Date.now() - 168 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 144 * 60 * 60 * 1000).toISOString(),
  },
];
